### ISSUE TITLE
How was the Youtube video generated?

### ISSUE THREAD

**Issue by iam-Shashank** [aleju/christmas-generator#1]
May I know how you generated the Youtube video in the README?

**Comment by aleju** [comment]
Steps:
1. Sample `N` random noise vectors, keep them fixed
2. Initialize network
3. Feed the noise vectors through the network to generate `N` images
4. Train for `M` batches
5. Repeat at step (3) until training is finished

That gives you `N` images every `M` training batches. Just combine every group of `N` images to a single image and then combine these images to a video.

**Comment by iam-Shashank** [comment]
Thanks!
